export const images = [
  new URL("../assets/flaga_META.png", import.meta.url).href,
  new URL("../assets/kostka_1oczko.png", import.meta.url).href,
  new URL("../assets/kostka_2oczka.png", import.meta.url).href,
  new URL("../assets/kostka_3oczka.png", import.meta.url).href,
  new URL("../assets/kostka_4oczka.png", import.meta.url).href,
  new URL("../assets/kostka_5oczek.png", import.meta.url).href,
  new URL("../assets/kostka_6oczek.png", import.meta.url).href,
  new URL("../assets/krzyzyk_odp.png", import.meta.url).href,
  new URL("../assets/NATO_flaga.png", import.meta.url).href,
  new URL("../assets/ONZ_flaga.png", import.meta.url).href,
  new URL("../assets/pionek.png", import.meta.url).href,
  new URL("../assets/plansza_dobra_odp.png", import.meta.url).href,
  new URL("../assets/Plansza_glowna.png", import.meta.url).href,
  new URL(
    "../assets/Plansza_pod_instruckje_i_wybor_poziomow.png",
    import.meta.url
  ).href,
  new URL("../assets/plansza_pod_pytanie.png", import.meta.url).href,
  new URL("../assets/Plansza_poziom1.png", import.meta.url).href,
  new URL("../assets/Plansza_poziom2.png", import.meta.url).href,
  new URL("../assets/plansza_przegrales.png", import.meta.url).href,
  new URL("../assets/plansza_zasadzka.png", import.meta.url).href,
  new URL("../assets/plansza_zla_odp.png", import.meta.url).href,
  new URL("../assets/PLANSZA.png", import.meta.url).href,
  new URL("../assets/plansza_wygrales_ukonczyles_poziom.png", import.meta.url)
    .href,
  new URL("../assets/pytanie_blankc.png", import.meta.url).href,
  new URL("../assets/strzalka_START.png", import.meta.url).href,
  new URL("../assets/szansa.png", import.meta.url).href,
  new URL("../assets/UE_flaga.png", import.meta.url).href,
  new URL("../assets/UNICEF_flaga.png", import.meta.url).href,
  new URL("../assets/wykrzyknik_do_instrukcji.png", import.meta.url).href,
  new URL("../assets/zasadzka.png", import.meta.url).href,
  new URL("../assets/znak_zapytania_do_instrukcji.png", import.meta.url).href,
];
